variables:
  APPLICATION_NAME: pod-viewer
  CONTAINER_IMAGE_NAME: ${APPLICATION_NAME}
  CONTAINER_IMAGE: ${AWS_ECR_PUBLIC_URL}/${APPLICATION_NAME}
  CONTAINER_IMAGE_TAGGED: ${CONTAINER_IMAGE}:${CI_COMMIT_TAG}
  K8S_NODEPORT: 31030
  K8S_SERVICEACCOUNT: moreillon

build-job:
  stage: build
  only:
    - tags
  before_script:
    - >
      aws ecr-public create-repository --region us-east-1 --repository-name ${APPLICATION_NAME}
      || echo "Repository might have already existed"

  script:
    - docker build -t ${CONTAINER_IMAGE} .
    - docker tag ${CONTAINER_IMAGE} ${CONTAINER_IMAGE_TAGGED}
    - docker push ${CONTAINER_IMAGE}
    - docker push ${CONTAINER_IMAGE_TAGGED}

deploy-job:
  stage: deploy
  only:
    - tags
  script:
    - envsubst < kubernetes_manifest.yml | kubectl apply -f -
  environment:
    name: production
    kubernetes:
      namespace: ${KUBERNETES_NAMESPACE}
